[package]
name = "gemini-client"
version = "0.1.0"
authors = ["Scott Kazimour <scottkaz@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.4"
url = "2.1.1"
clap = "2.33.1"
